### ISSUE TITLE
"python3 setup.py install gui" couldn't open gui

### ISSUE THREAD

**Issue by Mustangman1966** [xybu/onedrive-d#15]
the scrip "python3 setup.py install gui" gives:
"sage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'gui' "

How can I fix it?

**Comment by xybu** [comment]
It's not completed.
