### ISSUE TITLE
Unable to run on openSuSE 13.2 64-bit

### ISSUE THREAD

**Issue by joshuasb** [xybu/onedrive-d#20]
This is the error I get:
Error: setup script does not support your distro token msgnamsgdistributormsgnaechotmpdistribdesc

Ubuntu isn't the only or even the best Linux flavor around. OpenSuSE is quite popular and should be supported. I am very disappointed that it is not.

**Comment by xybu** [comment]
First, the question should be posted to onedrive-d-old repo.

Second, the shell script is just a shortcut for SOME linux distros including some versions of OpenSUSE. Apparently it cannot determine that your particular OpenSUSE version is "opensuse" because it got "msgnamsgdistributormsgnaechotmpdistribdesc" as the distro name.

Third, the README doc tells how to install the program manually.

**Comment by joshuasb** [comment]
Ok, wll how about this. I have daemonocle installed but I still can't install manually due to an error related to it. The last set of messages I get is this block:

Installed /usr/lib/python2.7/site-packages/onedrive_d-1.1.0dev-py2.7.egg
Processing dependencies for onedrive-d==1.1.0dev
Searching for daemonocle
Reading https://pypi.python.org/simple/daemonocle/
Download error on https://pypi.python.org/simple/daemonocle/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'daemonocle' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or download links found for daemonocle
error: Could not find suitable distribution for Requirement.parse('daemonocle')

This occurs whether I'm using the "old" repo or not.

**Comment by xybu** [comment]
Use python3.


Sincerely,
Xiangyu Bu

Sent from my Windows Phone
________________________________

**Comment by xybu** [comment]
The new repo does not rely on daemonocle.

Not sure why your Python package manager  cannot use https though.


Sincerely,
Xiangyu Bu

Sent from my Windows Phone
________________________________

**Comment by joshuasb** [comment]
I am using it

Sent from my HTC Tilt™ 2, a Windows® phone from AT&T

-----Original Message-----

**Comment by joshuasb** [comment]
If it weren't for the fact that I use https all the time on the web from school for other things, I'd suspect the college wifi.

Sent from my HTC Tilt™ 2, a Windows® phone from AT&T

-----Original Message-----

**Comment by joshuasb** [comment]
Ok, I was able to get a pull that let me install after removing and re-adding a bunch of packages, plus installing certain deps via pip3 instead of through YaST, but then I get a new error when I try to run it. You say the new repo doesn't require daemonocle, but here's the error:

Traceback (most recent call last):
  File "/usr/bin/onedrive-d", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: daemonocle

Which is odd because "sudo pip3 install daemonocle" says it's installed. I get a similar error on onedrive-prefs

Traceback (most recent call last):
  File "/usr/bin/onedrive-pref", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: daemonocle
