### ISSUE TITLE
File does not sync

### ISSUE THREAD

**Issue by meashsim** [xybu/onedrive-d#22]
I success Start and with status:
onedrive-d -- pid: 20194, status: sleeping, uptime: 0m, %cpu: 20.0, %mem: 1.0
But when check local directory on my Centos  did not see any files and no log in /var/log/onedrive_d.log
Any problem?
when i check on config_v2.json i saw "LAST_RUN_TIMESTAMP": "1970-01-01T00:00:00+0000"
Currently i used ICT time

**Comment by bondden** [comment]
I also would like to report the similar behavior (log,config_v2.json, running the service), except the fact that directories are synchronized but not files.
System: CentOS 7.
Thanks for the sw!

**Comment by xybu** [comment]
Close because it's supposed to be under xybu/onedrive-d-old repo.
For your question, if I remember correctly, that program doesn't write log to file. Nor does it use that timestamp. You could run program in debug mode to see the log.
