### ISSUE TITLE
Onedrive-d not uploading files and changes from local directory

### ISSUE THREAD

**Issue by spikespaz** [xybu/onedrive-d#24]
download works, not uploading changes. Is it possible that i need to start the daemon at boot manually?
does the program keep track of directory changes like deletion of folders and files or renames? does it have timestamps as to not overwrite newer data with that on the cloud?

**Comment by xybu** [comment]
Code for this repo not done yet.


Sincerely,
Xiangyu Bu

Sent from my Windows Phone
________________________________

**Comment by spikespaz** [comment]
wow that was fast thanks
