### ISSUE TITLE
Use official Python lib

### ISSUE THREAD

**Issue by xybu** [xybu/onedrive-d#25]
https://github.com/OneDrive/onedrive-sdk-python

**Comment by frazzmark** [comment]
:+1:

**Comment by xybu** [comment]
For record, the official SDK has a philosophy that one user can have at most one OneDrive Personal account and at most one OneDrive for Business account. This makes the architecture not fit well with onedrive-d. Now that I have what I need in onedrived.api, I won't bother migrating to official SDK.
