### ISSUE TITLE
Unable to run setup.py

### ISSUE THREAD

**Issue by duckulaj** [xybu/onedrive-d#28]
I am running Linux Mint 17.2 and trying to install onedrive-d. I have followed the instructions up to the point where the following command fails.

jonathan@Lenovo ~/Downloads/onedrive-d/onedrive-d-master $ python3 setup.py build
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_point'
  warnings.warn(msg)

Any assistance would be greatly appreciated

**Comment by bbakker** [comment]
Same kind of error here,
Using: Linux Mint 17.1 Rebecca

**Error**
sudo python3 setup.py build
/usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_point'
  warnings.warn(msg)
running build
running build_py
running egg_info
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing onedrive_d.egg-info/PKG-INFO
writing requirements to onedrive_d.egg-info/requires.txt
reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'

**Comment by rrioux** [comment]
Same here, with Fedora 23 x64:

[root@mobilemenace onedrive-d-master]# python3 setup.py build
/usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'entry_point'
  warnings.warn(msg)
running build
running build_py
running egg_info
writing top-level names to onedrive_d.egg-info/top_level.txt
writing dependency_links to onedrive_d.egg-info/dependency_links.txt
writing onedrive_d.egg-info/PKG-INFO
writing requirements to onedrive_d.egg-info/requires.txt
reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
writing manifest file 'onedrive_d.egg-info/SOURCES.txt'

**Comment by remyj38** [comment]
Just add a "s" to "entry_point".
https://github.com/xybu/onedrive-d/pull/29

**Comment by xybu** [comment]
Merged.
