### ISSUE TITLE
command: ./inst install (cd ~/Downloads/onedrive-d-master/ && ./inst install) wont work.

### ISSUE THREAD

**Issue by x-chadlin-x** [xybu/onedrive-d#3]
Hey, ive been trying and trying to install onedrive-d but whenever I go to do so, it dosnt work.

tutorials tell me to use the command "cd ~/Downloads/onedrive-d-master/ && ./inst install". However, when I do i get:
"chad@chad-Aspire-5551:~$ cd ~/Downloads/onedrive-d-master/ && ./inst install
bash: ./inst: No such file or directory"

Please help, ive tryed everything.

**Comment by xybu** [comment]
You must have referred to an outdated article discussing an outdated version of onedrive-d. As is said in the README.md of this repository, this repo is newly created and is not usable. For existing version, please go to https://github.com/xybu/onedrive-d-old and refer to the instructions there.
