### ISSUE TITLE
BUG: `stop` command don't seems to work correctly

### ISSUE THREAD

**Issue by regisf** [xybu/onedrive-d#32]
I've got a medium sized ~/OneDrive directory (1587 files for 8.4 Gbytes). The synchronization was done yesterday. When I start then I stop with 
```
$ onedrive-d start
$ onedrive-d stop
```

I've got a timeout error:
`ERROR: Timed out while waiting for process (PID XXX) to terminate`

onedrive-d continue to inspect the directory until I kill it with 

```
$ kill -9 XXX
``` 
Assuming of course that  XXX is the current processus ID 
Note: I've got a classical hard drive not  a SSD

**Comment by xybu** [comment]
That's for old repo. This new program does not deal with daemonization at all even if it keeps the 'd' suffix in its name.
