### ISSUE TITLE
missing package vendor 

### ISSUE THREAD

**Issue by leolivier** [xybu/onedrive-d#33]
The vendor package is needed when starting onedrived or onedrived-prefs but is missing in setup.py.
I just added the line: 
>        'onedrive_d.vendor',

after the line 
 >       'onedrive_d.tests.common',

in setup.py and restarted the build and install, then onedrived-prefs was able to start.
Now I still have problems on starting onedrived but still looking at them

**Comment by xybu** [comment]
Used find_packages to get rid of the hassle (73dda89a3d8345e242947089f0a73e4154340b0b).

The program hasn't reached "startable" stage yet. I am approaching the finish line though.
