### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kostaldavid8** [xybu/onedrive-d#4]
Python 3.4.3
Ubuntu 15.04
Installation failed

    Traceback (most recent call last):
      File "setup.py", line 13, in <module>
        from setuptools import setup
    ImportError: No module named 'setuptools'

**Comment by mariomatar** [comment]
I did 

    wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python


Then : 
	 % sudo python3 setup.py install                                
	running install
	Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
	/usr/bin/python3 -E -c pass
	TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
	running bdist_egg
	running egg_info
	writing requirements to onedrive_d.egg-info/requires.txt
	writing dependency_links to onedrive_d.egg-info/dependency_links.txt
	writing onedrive_d.egg-info/PKG-INFO
	writing top-level names to onedrive_d.egg-info/top_level.txt
	reading manifest file 'onedrive_d.egg-info/SOURCES.txt'
	writing manifest file 'onedrive_d.egg-info/SOURCES.txt'
	installing library code to build/bdist.linux-x86_64/egg
	running install_lib
	running build_py
	creating build/lib
	creating build/lib/onedrive_d
	copying onedrive_d/onedrive_gui.py -> build/lib/onedrive_d
	copying onedrive_d/onedrive_cli.py -> build/lib/onedrive_d
	copying onedrive_d/onedrive_pref_cli.py -> build/lib/onedrive_d
	copying onedrive_d/__init__.py -> build/lib/onedrive_d
	copying onedrive_d/onedrive_pref_gui.py -> build/lib/onedrive_d
	creating build/lib/onedrive_d/api
	copying onedrive_d/api/options.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/items.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/errors.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/clients.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/facets.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/identities.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/drives.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/resources.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/__init__.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/accounts.py -> build/lib/onedrive_d/api
	copying onedrive_d/api/restapi.py -> build/lib/onedrive_d/api
	creating build/lib/onedrive_d/cli
	copying onedrive_d/cli/__init__.py -> build/lib/onedrive_d/cli
	creating build/lib/onedrive_d/common
	copying onedrive_d/common/logger_factory.py -> build/lib/onedrive_d/common
	copying onedrive_d/common/path_filter.py -> build/lib/onedrive_d/common
	copying onedrive_d/common/fsman.py -> build/lib/onedrive_d/common
	copying onedrive_d/common/__init__.py -> build/lib/onedrive_d/common
	copying onedrive_d/common/netman.py -> build/lib/onedrive_d/common
	copying onedrive_d/common/userconf.py -> build/lib/onedrive_d/common
	creating build/lib/onedrive_d/store
	copying onedrive_d/store/userconf_db.py -> build/lib/onedrive_d/store
	copying onedrive_d/store/account_db.py -> build/lib/onedrive_d/store
	copying onedrive_d/store/items_db.py -> build/lib/onedrive_d/store
	copying onedrive_d/store/__init__.py -> build/lib/onedrive_d/store
	creating build/lib/onedrive_d/tests
	copying onedrive_d/tests/__init__.py -> build/lib/onedrive_d/tests
	creating build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/client_factory.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_resources.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/drive_factory.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_identities.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_drives.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/account_factory.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_errors.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_facets.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/__init__.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_items.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_options.py -> build/lib/onedrive_d/tests/api
	copying onedrive_d/tests/api/test_personal_account.py -> build/lib/onedrive_d/tests/api
	creating build/lib/onedrive_d/tests/common
	copying onedrive_d/tests/common/test_rest_client.py -> build/lib/onedrive_d/tests/common
	copying onedrive_d/tests/common/__init__.py -> build/lib/onedrive_d/tests/common
	copying onedrive_d/tests/common/test_network_mon.py -> build/lib/onedrive_d/tests/common
	creating build/lib/onedrive_d/ui
	copying onedrive_d/ui/__init__.py -> build/lib/onedrive_d/ui
	creating build/lib/onedrive_d/lang
	copying onedrive_d/lang/en_US.json -> build/lib/onedrive_d/lang
	creating build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/item_collection.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/drive.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/error_type2.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/error_type1.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/upload_session.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/personal_access_token.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/error_token_expired.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/error_server_internal.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/item_reference.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/image_item.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/drive_root.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/personal_access_token_alt.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/quota_facet.json -> build/lib/onedrive_d/tests/data
	copying onedrive_d/tests/data/photo_facet.json -> build/lib/onedrive_d/tests/data
	creating build/bdist.linux-x86_64/egg
	creating build/bdist.linux-x86_64/egg/onedrive_d
	creating build/bdist.linux-x86_64/egg/onedrive_d/cli
	copying build/lib/onedrive_d/cli/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/cli
	creating build/bdist.linux-x86_64/egg/onedrive_d/store
	copying build/lib/onedrive_d/store/userconf_db.py -> build/bdist.linux-x86_64/egg/onedrive_d/store
	copying build/lib/onedrive_d/store/account_db.py -> build/bdist.linux-x86_64/egg/onedrive_d/store
	copying build/lib/onedrive_d/store/items_db.py -> build/bdist.linux-x86_64/egg/onedrive_d/store
	copying build/lib/onedrive_d/store/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/store
	creating build/bdist.linux-x86_64/egg/onedrive_d/tests
	creating build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/item_collection.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/drive.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/error_type2.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/error_type1.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/upload_session.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/personal_access_token.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/error_token_expired.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/error_server_internal.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/item_reference.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/image_item.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/drive_root.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/personal_access_token_alt.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/quota_facet.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	copying build/lib/onedrive_d/tests/data/photo_facet.json -> build/bdist.linux-x86_64/egg/onedrive_d/tests/data
	creating build/bdist.linux-x86_64/egg/onedrive_d/tests/common
	copying build/lib/onedrive_d/tests/common/test_rest_client.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/common
	copying build/lib/onedrive_d/tests/common/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/common
	copying build/lib/onedrive_d/tests/common/test_network_mon.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/common
	creating build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/client_factory.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_resources.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/drive_factory.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_identities.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_drives.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/account_factory.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_errors.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_facets.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_items.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_options.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/api/test_personal_account.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests/api
	copying build/lib/onedrive_d/tests/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/tests
	copying build/lib/onedrive_d/onedrive_gui.py -> build/bdist.linux-x86_64/egg/onedrive_d
	copying build/lib/onedrive_d/onedrive_cli.py -> build/bdist.linux-x86_64/egg/onedrive_d
	creating build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/logger_factory.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/path_filter.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/fsman.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/netman.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	copying build/lib/onedrive_d/common/userconf.py -> build/bdist.linux-x86_64/egg/onedrive_d/common
	creating build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/options.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/items.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/errors.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/clients.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/facets.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/identities.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/drives.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/resources.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/accounts.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	copying build/lib/onedrive_d/api/restapi.py -> build/bdist.linux-x86_64/egg/onedrive_d/api
	creating build/bdist.linux-x86_64/egg/onedrive_d/lang
	copying build/lib/onedrive_d/lang/en_US.json -> build/bdist.linux-x86_64/egg/onedrive_d/lang
	copying build/lib/onedrive_d/onedrive_pref_cli.py -> build/bdist.linux-x86_64/egg/onedrive_d
	copying build/lib/onedrive_d/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d
	creating build/bdist.linux-x86_64/egg/onedrive_d/ui
	copying build/lib/onedrive_d/ui/__init__.py -> build/bdist.linux-x86_64/egg/onedrive_d/ui
	copying build/lib/onedrive_d/onedrive_pref_gui.py -> build/bdist.linux-x86_64/egg/onedrive_d
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/cli/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/store/userconf_db.py to userconf_db.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/store/account_db.py to account_db.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/store/items_db.py to items_db.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/store/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/common/test_rest_client.py to test_rest_client.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/common/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/common/test_network_mon.py to test_network_mon.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/client_factory.py to client_factory.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_resources.py to test_resources.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/drive_factory.py to drive_factory.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_identities.py to test_identities.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_drives.py to test_drives.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/account_factory.py to account_factory.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_errors.py to test_errors.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_facets.py to test_facets.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_items.py to test_items.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_options.py to test_options.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/api/test_personal_account.py to test_personal_account.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/tests/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/onedrive_gui.py to onedrive_gui.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/onedrive_cli.py to onedrive_cli.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/logger_factory.py to logger_factory.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/path_filter.py to path_filter.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/fsman.py to fsman.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/netman.py to netman.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/common/userconf.py to userconf.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/options.py to options.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/items.py to items.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/errors.py to errors.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/clients.py to clients.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/facets.py to facets.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/identities.py to identities.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/drives.py to drives.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/resources.py to resources.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/accounts.py to accounts.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/api/restapi.py to restapi.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/onedrive_pref_cli.py to onedrive_pref_cli.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/ui/__init__.py to __init__.cpython-34.pyc
	byte-compiling build/bdist.linux-x86_64/egg/onedrive_d/onedrive_pref_gui.py to onedrive_pref_gui.cpython-34.pyc
	creating build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	copying onedrive_d.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
	creating 'dist/onedrive_d-2.0.0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
	removing 'build/bdist.linux-x86_64/egg' (and everything under it)
	Processing onedrive_d-2.0.0-py3.4.egg
	creating /usr/local/lib/python3.4/dist-packages/onedrive_d-2.0.0-py3.4.egg
	Extracting onedrive_d-2.0.0-py3.4.egg to /usr/local/lib/python3.4/dist-packages
	Adding onedrive-d 2.0.0 to easy-install.pth file

	Installed /usr/local/lib/python3.4/dist-packages/onedrive_d-2.0.0-py3.4.egg
	Processing dependencies for onedrive-d==2.0.0
	Searching for ciso8601>=1.0.1
	Reading https://pypi.python.org/simple/ciso8601/
	Best match: ciso8601 1.0.1
	Downloading https://pypi.python.org/packages/source/c/ciso8601/ciso8601-1.0.1.tar.gz#md5=feb9bf324a903daeeee40d28d20960cb
	Processing ciso8601-1.0.1.tar.gz
	Writing /tmp/easy_install-eyz21ntd/ciso8601-1.0.1/setup.cfg
	Running ciso8601-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-eyz21ntd/ciso8601-1.0.1/egg-dist-tmp-1p0mn6a4
	module.c:1:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
	 #include <Python.h>

**Comment by xybu** [comment]
if you use Ubuntu, just install python3-setuptools package.


Sincerely,
Xiangyu Bu

Sent from my Windows Phone
________________________________

**Comment by xybu** [comment]
Please, do not use code in this repository. It is NOT usable at this stage. Please use the old version https://github.com/xybu/onedrive-d-old.

**Comment by kostaldavid8** [comment]
OK, now working. Thank you! I really appreciate your work on this project.
