### ISSUE TITLE
Debian 8: unable to execute 'x86_64-linux-gnu-gcc': No such file or directory

### ISSUE THREAD

**Issue by itbusters** [xybu/onedrive-d#6]
When installing at clean debian 8, i get:
`Running ciso8601-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-q2za1qjn/ciso8601-1.0.1/egg-dist-tmp-uad8r64_
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

to solve this issue you should do:
`apt-get install gcc`

next if you get:
`Running ciso8601-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tx6mfevs/ciso8601-1.0.1/egg-dist-tmp-a9gtbcvs
module.c:1:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

you should install python-dev:
`apt-get install python3-dev`

**Comment by xybu** [comment]
Thank you for reporting this. I have added a note to README that `gcc` is required. At least two packages will require CPython stack (`gcc`+`python3-dev`) -- ciso8601 and daemonocle. The former provides optimal efficiency for parsing datetime and the latter is the best (yet not ideal) daemonizer I've seen so far.

commit: ba90e8d5469347e71ff260c45eaec71a5072af73
