### ISSUE TITLE
how to run new onedrive

### ISSUE THREAD

**Issue by aurimrv** [xybu/onedrive-d#7]
Dear Xybu,

I run the command the install command using

sudo python3 setup.py install

The installations seams successfully. No error message.

auri@inct:~$ pip3 search onedrive-d
onedrive-d                - A Microsoft OneDrive daemon written in Python
  INSTALLED: 2.0.0
  LATEST:    0.6
auri@inct:~$ which onedrive-pref
auri@inct:~$ which onedrive-d
auri@inct:~$ which onedrive_d

But I cannot configure onedrive because I don't know how to execute the configuration command. Is it possible you give me some clue? Command which does not return where the executable are.

All the best
Auri

**Comment by xybu** [comment]
I thought I bolded the text in README that this repository is currently under construction and not usable at all.

If you need a working version, please use the code in onedrive-d-old repository.


Sincerely,
Xiangyu Bu

Sent from my Windows Phone
________________________________
